### ISSUE TITLE
Erlaube Scrolling in kurzen Texten

### ISSUE THREAD

**Issue by dodekeract** [HubertusWeber/Fefes-Blog-iOS#10]

**Comment by HubertusWeber** [comment]
Wozu? Ich sehe nicht ganz den Sinn.

**Comment by dodekeract** [comment]
@HubertusWeber it's how iOS is supposed to behave. Look at `Mail.app`.

If it's not scrollable it looks like it's frozen/broken. In addition to that, it's easier to read by allowing you to scroll down paragraphs that you've already read.

**Comment by HubertusWeber** [comment]
Guter Punkt, wird implementiert.
