### ISSUE TITLE
Search: Abbrechen Button

### ISSUE THREAD

**Issue by markusjaehn** [HubertusWeber/Fefes-Blog-iOS#16]
What is the use of the _Abbrechen_ button in the search tab?

**Comment by HubertusWeber** [comment]
Das Abbrechen der Suche und damit das Ausblenden der Tastatur.

**Comment by markusjaehn** [comment]
Das Ausblenden der Tastatur über den Tastatur-Einziehen-Button (i.d.R. in der Tastatur unten rechts; du weißt was ich meine?) ist keine Option?

Mir persönlich gefällt der Abbrechen Button nicht! _(subjektive Meinung)_

**Comment by HubertusWeber** [comment]
Vielen Dank für Deinen Einwand, allerdings möchte ich mich so dicht, wie möglich an die Standard iOS Apps halten, ich will
schließlich die Standard Fefes Blog app für iOS werden. Wenn Du Dir beispielsweise die Suche in den Systemeinstellungen anschaust, dann verhält diese sich diesbezüglich genau so.

**Comment by markusjaehn** [comment]
> Wenn Du Dir beispielsweise die Suche in den Systemeinstellungen anschaust

Hier gibt es aber nur einen Button, welcher das Feld sowie die Suchergebnisse zurücksetzt (und noch ein bisschen mehr macht).

Deine Suche und die iOS Settings sind schlecht zu vergleichen, da die Settings die Suche mehr in einem 'Overlay' machen und deine App die Suche als festen Tab hat.

Ich denke, dieses Thema müssen wir noch einmal diskutieren, deswegen reopen.
