### ISSUE TITLE
Search: Reset

### ISSUE THREAD

**Issue by markusjaehn** [HubertusWeber/Fefes-Blog-iOS#17]
By resetting the search bar the app should also reset the result list.

**Comment by HubertusWeber** [comment]
Was meinst Du mit "resetting"? Meinst Du das löschen des Inputs? Welchen Mehrwert hätte es, dass die Suchergebnisse dann verschwinden würden?

**Comment by markusjaehn** [comment]
Genau, ich meine das Löschen des Inputs über das kleine (x) im Eingabefeld.

Mehrwert ist, dass du damit entsprechend des Standards arbeiten würdest. (siehe iOS-, Facebook- oder Whatsapp-Suche)

**Comment by HubertusWeber** [comment]
Der Unterschied ist, dass die Beispiele, die Du angeführt hast alle eine Live Suche haben. Dort macht es absolut Sinn, dass die Ergebnisse weg sind, wenn die Eingabe weg ist. Das Fefes Blog iOS aus performance Gründen keine Live Suche hat, werden die Ergebnisse immer dan aktualisiert, wenn Du auch Suchen tippst. Aus meiner Sicht macht es keinen Sinn die Ergebnisse künstlich zu löschen, wenn Du die Eingabe löscht, da es keinen Mehrwert hat (ich meine Du hast nichts davon, wenn die Liste auf einmal leer ist) und das einzige was passieren kann ist, dass Du aus Versehen darauf tippst und jetzt Deine Ergebnisse weg sind.

**Comment by HubertusWeber** [comment]
Mit der Implementierung von #23 bekommst Du dann wohl doch genau das hier 😉
