### ISSUE TITLE
Anzeige ob Lesezeichen bereits gesetzt

### ISSUE THREAD

**Issue by markusjaehn** [HubertusWeber/Fefes-Blog-iOS#21]
Klickt man im Main Feed auf die Einträge ist nicht ersichtlicht, ob bereits ein Lesezeichen gesetzt wurde oder nicht.

Vielleicht lässt sich das Lesezeichen-Symbol entsprechend färben. (zum Beispiel blau hinterlegt, wenn das Lesezeichen für diesen Eintrag bereits gesetzt wurde)

**Comment by HubertusWeber** [comment]
Ist in Build 8 implementiert, wie vorgeschlagen.
Danke für den Hinweis <3
