### ISSUE TITLE
Initialer Lesezeichen-View

### ISSUE THREAD

**Issue by markusjaehn** [HubertusWeber/Fefes-Blog-iOS#22]
Der Lesezeichen-View sieht (logischerweise) leer aus, wenn man die App frisch installiert hat.

Vielliecht könnte, wenn noch kein Lesezeichen gesetzt ist, hier ein Hinweis stehen, wie Lesezeichen gesetzt werden können.

**Comment by HubertusWeber** [comment]
Ist genau so in Build 8 umgesetzt.
