### ISSUE TITLE
Suchen-View: Suchvorschläge

### ISSUE THREAD

**Issue by markusjaehn** [HubertusWeber/Fefes-Blog-iOS#23]
Ist keine Suche getätigt worden, ist der Suchen-View leer. Hier wäre Platz, um beispielswiese die letzten Suchanfragen des Benutzers zur erneuten Suche anzuzeigen, oder _trending_ Suchanfragen, welche von allen Benutzern häufig gesucht wurden, anzuzeigen.

**Comment by HubertusWeber** [comment]
Sehr gute Idee, kommt auf jeden Fall in eine der nächsten Beta Builds.

**Comment by HubertusWeber** [comment]
Ist in Build 7 implementiert.
