### ISSUE TITLE
Gesten

### ISSUE THREAD

**Issue by HubertusWeber** [HubertusWeber/Fefes-Blog-iOS#25]
Swipe Gesten hinzufügen, zum Beispiel:
- Post nach rechts swipen um Lesezeichen hinzuzufügen
- Post links swipen um als gelesen zu markieren
- Post in den Lesezeichen swipen um wieder zu entfernen

Bin für weitere Vorschläge hier im Issue sehr gerne offen. Vielen Dank schonmal im Voraus.

**Comment by dodekeract** [comment]
Ich bin für Gelesen + Share Extension. Im besten Fall machst du's so wie Apollo:
<img width="417" src="https://user-images.githubusercontent.com/1133858/37340497-9b7b554c-26be-11e8-9e6e-46b9189a9466.png">

**Comment by HubertusWeber** [comment]
In Build 10 implementiert
