### ISSUE TITLE
Search Bar Redesign

### ISSUE THREAD

**Issue by dodekeract** [HubertusWeber/Fefes-Blog-iOS#3]

**Comment by HubertusWeber** [comment]
Kommt wahrscheinlich in Build 6

**Comment by HubertusWeber** [comment]
Ich habe relativ viel mit verschieden Suchfelddesigns rumprobiert und bin zum Ergebnis gekommen, dass es mir so wie es aktuell ist am Besten gefällt. Es wird wahrscheinlich für version 1.2 (oder vielleicht 1.3) so wie so einstellbare Designs geben, dann kannst Du es ändern, wenn es Dir nicht gefällt, aber vorerst bleibt es so wie es momentan ist.
