### ISSUE TITLE
Fehlerhafte Anzeige

### ISSUE THREAD

**Issue by mkay-sh** [HubertusWeber/Fefes-Blog-iOS#30]
Manchmal werden einige Posts falsch angezeigt und lassen sich nicht mehr lesen. Nach einigen Tagen behebt sich das Problem von selbst.
![img_1744](https://user-images.githubusercontent.com/24921097/45807705-5f1abd80-bcc4-11e8-8077-d89632cdb06d.png)

**Comment by HubertusWeber** [comment]
Hey,
Vielen Dank für und sorry für die späte Antwort. Das Problem entsteht durch einen Fehler im Übertragungsformat. Ich habe erstmal kurzfristig die Posts bei denen das Problem auftritt serverseitig geblockt und der Fehler ist in Version 1.1 behoben, die wartet gerade auf den Review von Apple.
LG Hubertus

**Comment by HubertusWeber** [comment]
Version 1.1 steht zum Download via App Store zur Verfügung.
