### ISSUE TITLE
Seit 1.11 alle Posts doppelt inkl gelesen Status

### ISSUE THREAD

**Issue by bew99** [HubertusWeber/Fefes-Blog-iOS#31]
V1.1 B16

Ich hänge unten noch ein Bild an.
Restart der App hat nicht geholfen, nach den reload war das Ergebnis das selbe, alle Posts doppelt.

![c2188a62-0009-489e-b66b-b64a217b6792](https://user-images.githubusercontent.com/1237115/47909332-e34d8c80-de8f-11e8-9bf6-6b2af0bd3920.png)

**Comment by dodekeract** [comment]
Same here.

**Comment by dodekeract** [comment]
@bew99 does this still happen for you or can this issue be closed?

**Comment by HubertusWeber** [comment]
Heyho!
Vielen Dank für den Report. Entschuldigt den späten Fix, sollte jetzt behoben sein.
