### ISSUE TITLE
Absturz beim Versuch einen Link zu öffnen

### ISSUE THREAD

**Issue by JustMedium** [HubertusWeber/Fefes-Blog-iOS#33]
Beim Versuch den zweiten Link aus dem Artikel „https://blog.fefe.de/?ts=a5223d9d“ zu öffnen stürzt die App ab und schließt sich.

**Comment by dodekeract** [comment]
Can reproduce.

**Comment by HubertusWeber** [comment]
Danke für Dein Feedback. Ich habe den Fehler in der Version 1.1.1 behoben.
