### ISSUE TITLE
Render Text like Safari Reader Mode

### ISSUE THREAD

**Issue by dodekeract** [HubertusWeber/Fefes-Blog-iOS#7]
Improves readability and looks familiar.

**Comment by HubertusWeber** [comment]
Safari Reader Mode lässt den Benutzer tatsächlich zwischen verschiedenen Schriftarten auswählen, das ist tatsächlich eine gute Idee aber ein anderes Issue: #14

**Comment by dodekeract** [comment]
@HubertusWeber Es geht nicht um die Fonts. Der issue ist eher dass Safari Reader Mode den Text 100x besser darstellt bzw. formatiert.

**Comment by HubertusWeber** [comment]
Gute Idee, an der Formatierung zu arbeiten, aber ich habe das mal in ein separates Issue (  #15 ) gemacht, weil ich das nicht unbedingt so dicht an Safari Reader binden möchte.
