### ISSUE TITLE
Haptic Feedback

### ISSUE THREAD

**Issue by dodekeract** [HubertusWeber/Fefes-Blog-iOS#8]
E.g. when changing the font size to default. #5

**Comment by HubertusWeber** [comment]
Geplant für Version 1.0.

**Comment by HubertusWeber** [comment]
Ist in Build 9 für alle bestehenden Funktionen, bei denen es Sinn macht hinzugefügt.
Werde in Zukunft darauf achten es direkt einzubauen.
